# Use uma imagem base do Node.js
FROM node:14

# Define o diretório de trabalho dentro do container
WORKDIR /app/backend

# Copia os arquivos package.json e package-lock.json para o diretório de trabalho
COPY /backend/ ./

EXPOSE 4000

